// Auto-generated by: pnpm supabase gen types typescript --local > src/types/database.ts
// Run this command after migrations are applied.
//
// NOTE: The `profiles` table below is a manual placeholder that mirrors the
// application domain types in `@/types/index.ts`. It unblocks type-safe
// Supabase queries until the DB migrations in `gestione-turni-db` are applied
// and types can be regenerated from the real schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          role: "manager" | "employee";
          workplace_id: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          phone?: string | null;
          role: "manager" | "employee";
          workplace_id?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          role?: "manager" | "employee";
          workplace_id?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
